env:
  global:
    - secure: MIX+jzvF4YwoEfebyX4K5cSx3WIk9QQusvVGW+qZneB/CI3zzraiZXS58M258Pv4sXPDBQ9iGPRBAKtjb3EnZMy14i0gQT7SX6pJbJ6Ur8An+75fWgAJ2NutOjI1N7TDVQufqdG1qoLf/VBvtmuoiEnor7gkxdEHOVCTB9I/Kbd1c65wK927nZqYLQ/voWojIIR5ZgoMP0cVQw5bk75ZvhHngKmGMkqvW5o4XPOE/ja2dmiJ3DOBCDAXRKEg82+qdDkrn2UcNYs/K6vIlBzJ9q3kh606ffNnOidP8L27zupk8F91f5Wa34tKX2pu/XyBuFn7riff2OcXSLIcTaxunZAM9t2BtIzrZ0e1pJgCYv3K2GCdJI91wjLZEu35Kk7GBOhFFn0wmoiWcraiIVCctP/wDaPAzrm5Hv0Po1EIZC2WcrbzxWPwqzPBpIKUlZ76xSO2Q6pFTf4mQ7nmDdAwC0UPxS7NDKxV6COoR61jMVjM4ge8PqdWjWXaGg7yg32evifAwZuYUA7P5fuxIjP6qokEIQ6UVkOjKj+txYYcgqSUuAowalYTXxHDsIFxb4cOsDcBxOyrBtoUa+O5lW6eD+lLRykaagM5Cj8/rhyWz3OfpQW36hRFzpkryY6KjIc0cmxegB2PMvsDFZ0nLH2QDDI4ZyUTAakm/Lqpl5X9S/c=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/firehol_level1
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
