env:
  global:
    - secure: r2eqrQoSV7WVa+alHK7hzEZavVq/oKI04nSEpyrLCY7UrP3xfW9eom454EbwSnPVWyAGeTgv5Ld0uhaajfnjA/LH2kXI7AQjxf7cA0X3wzhyxTKrL6FYeFe4JXnLJ7opqXgFpiZl/TwQ7qVeqi1yWiucqQoY+1LEjKQd+2K+J+yUahGZyF6LTKqLe6EclEOS84EnwGx5J8pqZYbG0X8I8IaLVDw5p9EtisDMwFwCIzKYIpeMRHT9avmYVRU/bzBTPwVnvIsYM1n43hzD1nIzaQRLyFIoSv2AK/u/x/bOrrxR0/gsrTyH92syqhX0gULEEOVFXDdbkbxhE34ILkxXP4cbBscIvqkSPImP8/NK4wCNW+brM9jWbAjEuyf0IqYZCLE7MGDBc/T9K63O47sT/xJNIKm6Rk+x7X/tWflZnIiX+w16SvJfCzT5I/fJwKtMS2Gul8qp5ZfHiIkPh8gsh4r0E7HLVMer6TWQrL05AFc8KWBDykxRKLpgRMJMUnM77GYj92tJUDcvrp0RFvgGx4fHIUV9YXmupXvJdpioQxzQCryDCjJnuxWEEABwClHgJw68js52uZ6qCt7p7CwHhuK8XF17UUxkXXRdgj/XPXT96d40hqo/X/dlVNgyIQwOoF/JxemCbNdNVX+e5SkZKon9/kaiIO8YJ7BXNrcdqE4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/firehol_level1
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
