env:
  global:
    - secure: Su1CiZLRfO+L9GxkuiBbmJWsoNB+YyFwhNyw8xzYXHpguwq/421X2rDjy+bss0QOedeFrV7ogfRRHL3M57aOfL5dT/eAIRqRNhnho1yejv2GZhgpAEcMJkUrBFdSUfg6X9NlzxjJzNEl9ixx3+QkEcPttUHejOlAC8LNAptzoQoD7ImCYrM0MDHaWGDC4BeLKEALsjcL5q7/UUPw0Tn5Dz9YSbDfhYCMFAA4ZqTg/gZ83cc122jTxxDvd/QYfn7jDZGBeLOUx3MEsn15nc13R+bE9UvM5TxkPF1aQkqXFKGpGLGxsWCgPklAVTci3XTwoVB5sJAuBfmH2gZA4dU9YewzTEjOUrGMq3ldFJRA0PszYF53hwEO1nzmdKt0qg1ksr38EfHicwmYWrhD+frIZ+b2PlYGNYce/1QQEIujxeie3noIi++r19NRzBDWDIcPdaAt3pJCdk+junzfdmPBuVmW2aujis9Dfm+lAH/rM4pUX/R/aeFLTGTpvO7xWyRlr2pG1JEV+Ny+g6pSn+BSoVz1dmrYUZuEYiJQHmKkRDjwZWW8e8OBNps0mHF06kGmg9eFiKo7JeClQicFYfCB1TjDeQxAqYMSSlAYqdB5k7o1T9O645hzfOyyq9oq7sXf97Mcp+XPf9MFWjRrgeQQUtRkC9/CcnOWGQVf714QY0o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/firehol_level1
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
