env:
  global:
    - secure: aMvjsIVxr4jSlwmIsAhcAPjntt2KwxEvrZzH5Q8UUkIf1ekTE5W5ZJcoZtFKMSotZmcYMNklasXeXQvDmAGkyeQS3wJLwONALI+nAg7+YS/DaZ44fNtx+8AlHhPwLRw/alRs8H3aYSyHEdWb8RsVXps6S8etWWb9qz4PjC6QDWZvYO3JCk9mBpLLoqu9R4gg03G5IVYqNg/RYNMbd4VPcielbxZlQUukkeKfbPf3CTTt/DipSRqd56/c2MC4AN1qaM39qijUtuxQw3d0Y9jH6ys17VCYGlKV1Mfj5Dg7ZkjqwsA3Fe6L3nG48fU6hN2hkzDmdmMZ0pc02Hn9phEPbFBJeDRcgzDpTD5Qyar2qAIGxjwLqiu8cO4Fk6WBZRsZyaMrQwXfGPufF+Ud8A/9rv53/OMCjreFy7FvuXccWoFCKpUG6safIgSDqyghIYCJSR8I+b5CgWbDTZ1YALwm7n4Y7zI2cvbK9cyxVKXM5daY3cqXla1z6jE2n+usZWZ6g4Nkbpzvhx2cJDTHX8dyxSYT/s5rnjpnmT87X0IUuRRaaa63qfSSpVon+pcbGdxuVAoRucBNDY7SrQCsCxgb/KO6G+DOPXdhjW5L3Ebr7h1hxgp1CfIvpLZu8UsYMoibi2K2kK3ub5cIK2i9wxg+9Xnj4WHdrgUVGPVJd3ICqm4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/firehol_level1
    - GIT_BRANCH: master
    - WHITELISTING_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/dev-center/whitelisting/whitelisting.py
    - UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    - ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests
  - wget "${WHITELISTING_LOCATION}" -o /dev/null -O whitelisting.py && chmod +x whitelisting.py
  - if [[ ! -f .admin ]]; then wget "${UPDATE_LOCATION}" -o /dev/null -O update.py && chmod +x update.py; else echo "No need to download/update update.py."; fi
  - if [[ ! -f .admin ]]; then wget "${ADMINISTATION_LOCATION}" -o /dev/null -O administration.py && chmod +x administration.py; else echo "No need to download/update administration.py."; fi

script:
  - python3 ./update.py

notifications:
  on_success: change
  on_failure: always
